name: fixnum
version: 1.0.0

description: >-
  Library for 32- and 64-bit signed fixed-width integers with consistent
  behavior between native and JS runtimes.
homepage: https://github.com/dart-lang/fixnum

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0-nullsafety
